function rollDarkness(players: players, amount: integer = 1):
    loop {_amount} times:
        set {_rp} to a random player out of {_players::*}
        remove {_rp} from {_players::*}
        set {StarlightLife::Apocalypse::Darkness::%size of {StarlightLife::Apocalypse::Darkness::*} + 1%} to uuid of {_rp}
    send title "&aLight" to {_players::*} 
    send "&aYou are Light! You are normal!" to {_players::*}
    send title "&5The Darkness" to players from {StarlightLife::Apocalypse::Darkness::*}
    loop players from {StarlightLife::Apocalypse::Darkness::*}:
        set {_darknessText} to ""
        loop {StarlightLife::Apocalypse::Darkness::*} where [input != uuid of loop-value]:
            set {_player} to player from loop-value-2
            set {_player} to offline player from loop-value-2 if {_player} isn't set
            set {_prefix} to ", " if loop-iteration-2 >= 2 else ""
            set {_darknessText} to {_darknessText} + "%{_prefix}%<%team color of team of {_player}%>%{_player}%<gray>"
        send formatted "&7You are &5&lThe Darkness&r&7, all of your teams are invalid and your goal is now to infect all the other light players and convert them into Dark Matter via killing them direct or indirect, you act as a leader to the Dark Matter as you are the root of the infection, therefore if you die all existing Dark Matter will also lose 10 starlight. if you fail to convert every other player into Dark Matter you will be set down 2 Life Colors, you may kill other Dark Matter and Darkness players if you wish however this will not contribute towards your overall goal. %{_darknessText}% is the other Darkness, you may work with them to infect the rest of the players" to loop-value
    set {StarlightLife::Apocalypse::Light::*} to (uuid of {_players::*}) where [{StarlightLife::Apocalypse::Darkness::*} doesn't contain input]

function failDarkness():
    loop {StarlightLife::Apocalypse::Darkness::*}:
        remove 2 from {StarlightLife::Data::%loop-value%::Lives}
        set {StarlightLife::Data::%loop-value%::Starlight} to 100
        if {StarlightLife::Data::%loop-value%::Lives} <= 0:
            set {StarlightLife::Data::%loop-value%::Lives} to 1
        UpdateTeam(offline player from loop-value)
    loop {StarlightLife::Apocalypse::DarkMatter::*}:
        remove 1 from {StarlightLife::Data::%loop-value%::Lives}
        set {StarlightLife::Data::%loop-value%::Starlight} to 100
        if {StarlightLife::Data::%loop-value%::Lives} <= 0:
            set {StarlightLife::Data::%loop-value%::Lives} to 1
        UpdateTeam(offline player from loop-value)
    send title "&cYou have failed!" to players from ({StarlightLife::Apocalypse::Darkness::*} and {StarlightLife::Apocalypse::DarkMatter::*})
    clear {StarlightLife::Apocalypse::Darkness::*} and {StarlightLife::Apocalypse::DarkMatter::*}
    broadcast "&5Throughout the relentless and violent night, a dim light shines through the despair of circumstance and the Light has triumphed over the night. Roles Cleared!"
    
function cureDarkness():
    loop {StarlightLife::Apocalypse::Darkness::*} and {StarlightLife::Apocalypse::DarkMatter::*}:
        set {_p} to player from loop-value
        send title "&aYou have succeeded!" to {_p}
        if {_p} isn't set:
            set {_p} to offline player from loop-value
        UpdateTeam({_p})
    clear {StarlightLife::Apocalypse::Darkness::*} and {StarlightLife::Apocalypse::DarkMatter::*}
    

on death of player with priority lowest:
    damage cause isn't custom
    wait 1 tick
    if any:
        {StarlightLife::Apocalypse::Darkness::*} contains uuid of victim
        {StarlightLife::Apocalypse::DarkMatter::*} contains uuid of victim
    then:
        if {StarlightLife::Apocalypse::Darkness::*} contains uuid of victim:
            loop {StarlightLife::Apocalypse::DarkMatter::*}:
                remove 10 from {StarlightLife::Data::%loop-value%::Starlight}
                if {StarlightLife::Data::%loop-value%::Starlight} <= 0:
                    remove 1 from {StarlightLife::Data::%loop-value%::Lives}
                    if {StarlightLife::Data::%loop-value%::Lives} = 0:
                        Eliminate(player from loop-value)
                        set death message to "&c%uncolored death message%"
                        stop
                    set {StarlightLife::Data::%loop-value%::Starlight} to 100
                    colorChange(player from loop-value)
                send formatted "<%team color of team of victim%>%victim%<gray> has died. <red>You have lost 10 ☆" to player from loop-value

            loop {StarlightLife::Apocalypse::Darkness::*} where [input != uuid of victim]:
                remove 10 from {StarlightLife::Data::%loop-value%::Starlight}
                if {StarlightLife::Data::%loop-value%::Starlight} <= 0:
                    remove 1 from {StarlightLife::Data::%loop-value%::Lives}
                    if {StarlightLife::Data::%loop-value%::Lives} = 0:
                        Eliminate(player from loop-value)
                        set death message to "&c%uncolored death message%"
                        stop
                    set {StarlightLife::Data::%loop-value%::Starlight} to 100
                    colorChange(player from loop-value) 
                send formatted "<%team color of team of victim%>%victim%<gray> has died. <red>You have lost 10 ☆" to player from loop-value
        if size of {StarlightLife::Apocalypse::DarkMatter::*} >= 12:
            updateInfectedTeam(victim)
        stop
    if any:
        {StarlightLife::Apocalypse::Darkness::*} contains uuid of attacker
        {StarlightLife::Apocalypse::DarkMatter::*} contains uuid of attacker
    then:
        add uuid of victim to {StarlightLife::Apocalypse::DarkMatter::*}
        remove uuid of victim from {StarlightLife::Apocalypse::Light::*}
        while victim is not alive:
            wait 1 tick
        send "&7You are &8&lDark Matter&r&7, you have been &cinfected&7 and must work with other &8&lDark Matter&r&7 as well as &5&lThe Darkness&r&7 infect every other player via killing them direct and indirect, all teams are void while you are &8&lDark Matter&r&7 and if you fail to infect every Light player you will be set down to the next Life Color, you may kill other Dark Matter however this will not help your overall goal." to victim
        set glowing of victim to false
        if size of {StarlightLife::Apocalypse::Light::*} = 0:
            cureDarkness()
        if size of {StarlightLife::Apocalypse::DarkMatter::*} >= 6:
            loop {StarlightLife::Apocalypse::DarkMatter::*} and {StarlightLife::Apocalypse::Darkness::*}:
                updateInfectedTeam(offline player from loop-value)
        if (size of {StarlightLife::Apocalypse::DarkMatter::*} + size of {StarlightLife::Apocalypse::Darkness::*}) >= 10:


#local function lightPeriodicGlow(interval: timespan):

                
function updateInfectedTeam(player: player):
    if {StarlightLife::Apocalypse::DarkMatter::*} < 12:
        UpdateTeam({_player}) 
    else if {StarlightLife::Apocalypse::DarkMatter::*} contains uuid of {_player}:
        set team color of team of {_player} to dark gray
    else if {StarlightLife::Apocalypse::Darkness::*} contains uuid of {_player}:
        set team color of team of {_player} to dark purple
    else:
        UpdateTeam({_player})
    


on tab complete of "/starlightlife", "/sl", "/life:starlightlife" and "/life:sl" with priority lowest:
    add "apocalypse" to tab completions for position 1







command /rolldarkness:
    description: description
    permission: permission
    trigger:
        broadcast all enabled scripts
        broadcast true if "%all enabled scripts%" contains "infection.sk"
    
command /getdarkness:
    description: description
    permission: permission
    trigger:
        broadcast "Darkness: %{StarlightLife::Apocalypse::Darkness::*}%"
        broadcast " "
        broadcast "Dark MAtter: %{StarlightLife::Apocalypse::DarkMatter::*}%"

